### ISSUE TITLE
ct.CDLL("CsoundLib64.framework/CsoundLib64")  fails

### ISSUE THREAD

**Issue by ricktaube** [csound/ctcsound#19]
Hi I cant get csound to process a file using ctcsound.py.

I installed the latest version of Csound for mac, my csound version is:   --Csound version 6.15 (double samples) Nov 20 2020

My Csound lib is installed in:  /Library/Frameworks/CsoundLib64.framework/Versions/6.0/CsoundLib64 

My ctcsound.py is installed in:  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ctcsound.py

When I run my script 

	$ python3.9 -m musx_demos.musx-csound-demo,  it works upto line 47:

	libcsound = ct.CDLL("CsoundLib64.framework/CsoundLib64")

and then it cant actually load the library. I have no idea how to fix this problem, any advice appreciated!

Here is Python’s stack trace:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/taube/Classes/mus499mrc/Sources/musx_demos/musx-csound-demo.py", line 19, in <module>
    import ctcsound
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ctcsound.py", line 47, in <module>
    libcsound = ct.CDLL("CsoundLib64.framework/CsoundLib64")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(CsoundLib64.framework/CsoundLib64, 6): image not found

Rick Taube
________________________________
Chair, Composition/Theory
School of Music
University of Illinois Urbana-Champaign
Email: taube@illinois.edu
President, Illiac Software Inc.
https://harmonia.illiacsoftware.com/
Email: taube@illiacsoftware.com

**Comment by pmsorhaindo** [comment]
Same here, did you get to the bottom of this?
